// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5BT337jU5yEaco3UWOPAnauCeqgNfQ2w',
    appId: '1:204562390170:web:8b7883f057cc8a3c579323',
    messagingSenderId: '204562390170',
    projectId: 'aslan-de6bf',
    authDomain: 'aslan-de6bf.firebaseapp.com',
    storageBucket: 'aslan-de6bf.firebasestorage.app',
    measurementId: 'G-YD6NB0CM9N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxznyFetYL2-tIkAH0dTqvfpIBCtGx6LM',
    appId: '1:204562390170:android:5a2385f8276a6d96579323',
    messagingSenderId: '204562390170',
    projectId: 'aslan-de6bf',
    storageBucket: 'aslan-de6bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC547YBwZ57XUx9P7EelzPtTAkUoyVHFUs',
    appId: '1:204562390170:ios:e920eb6c34cf815d579323',
    messagingSenderId: '204562390170',
    projectId: 'aslan-de6bf',
    storageBucket: 'aslan-de6bf.firebasestorage.app',
    iosBundleId: 'com.example.sneakerStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC547YBwZ57XUx9P7EelzPtTAkUoyVHFUs',
    appId: '1:204562390170:ios:e920eb6c34cf815d579323',
    messagingSenderId: '204562390170',
    projectId: 'aslan-de6bf',
    storageBucket: 'aslan-de6bf.firebasestorage.app',
    iosBundleId: 'com.example.sneakerStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5BT337jU5yEaco3UWOPAnauCeqgNfQ2w',
    appId: '1:204562390170:web:d4ec531381b5f9f4579323',
    messagingSenderId: '204562390170',
    projectId: 'aslan-de6bf',
    authDomain: 'aslan-de6bf.firebaseapp.com',
    storageBucket: 'aslan-de6bf.firebasestorage.app',
    measurementId: 'G-XMPWEXC4SW',
  );
}
